# Generated by Django 5.2.3 on 2025-07-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('slno', models.IntegerField(primary_key=True, serialize=False)),
                ('desccription', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
