# Generated by Django 5.2.3 on 2025-07-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='desccription',
            new_name='description',
        ),
    ]
