# Generated by Django 5.2.3 on 2025-07-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_todo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='todotask',
            fields=[
                ('slno', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
