# Generated by Django 5.2.3 on 2025-07-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_todotask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotask',
            old_name='date',
            new_name='due_date',
        ),
    ]
